name: test

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'readme.*'
      - 'logo/*'
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - 'readme.*'
      - 'logo/*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim-version: ['1.4.8', 'stable']
    steps:
      - uses: actions/checkout@v1
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}
      - run: nimble install -Y
      - run: nimble tests -Y
